- name: Setup gcloud environment
  uses: GoogleCloudPlatform/github-actions@0.1.2

- name: Google Java Format
  uses: axel-op/googlejavaformat-action@v3.1.0

# Example workflow
name: Format

on: [push, pull_request]
  
jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      # Recommended: latest versions of Google Java Format require JDK 11+
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
